version: "3.3"
services:
  web:
    build:
      context: .
      args:
        RUBY_VERSION: "2.7.2"
        BUNDLER_VERSION: "2.1.2"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_URL: postgres://postgres:changeme@db
    volumes:
      - .:/myrailsapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust



